
spring.application.name=nullnet-backend
server.port=9001

# H2 LOCAL FILE-PERSISTENT DATABASE - ONLY FOR LOCAL DEVELOPMENT & TESTING SCOPE
spring.datasource.url=jdbc:h2:file:./data/localdb;MODE=PostgreSQL

# PROVIDES A WEB BROWSER H2 CONSOLE AT /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DEPLOYMENT-USABLE DATABASE SETTINGS
spring.jpa.properties.hibernate.default_schema=public
#spring.datasource.driver-class-name=org.postgresql.Driver # will need "jdbc:postgresql:" url instead of "jdbc:h2:" url to use postgres driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# only "none" or "validate" should be used in a deployment project, and DDL should be handled elsewhere
spring.jpa.hibernate.ddl-auto=create-drop

# logging config
logging.file.name=application.log
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.network.thenull.api=DEBUG

# increase maximum upload size from the default 1MB (implemented for thumbnail API)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
